"""empty message

Revision ID: 10ab08fc321b
Revises: ba7716dca30a
Create Date: 2023-02-25 15:47:37.542906

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = '10ab08fc321b'
down_revision = 'ba7716dca30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_task_id', table_name='file')
    op.create_index(op.f('ix_file_task_id'), 'file', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_task_id'), table_name='file')
    op.create_index('ix_file_task_id', 'file', ['task_id'], unique=False)
    # ### end Alembic commands ###
