"""empty message

Revision ID: 77c100300b5b
Revises: 10ab08fc321b
Create Date: 2023-04-06 10:45:47.289554

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '77c100300b5b'
down_revision = '10ab08fc321b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'task',
        'from_user_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        'task',
        'message_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'task',
        'message_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        'task',
        'from_user_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
