"""empty message

Revision ID: 8021be777d1d
Revises: ff03785a1f0d
Create Date: 2022-06-13 20:16:10.845151

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8021be777d1d'
down_revision = 'ff03785a1f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('from_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'from_user_id')
    # ### end Alembic commands ###
