"""empty message

Revision ID: ba7716dca30a
Revises: 8021be777d1d
Create Date: 2022-06-13 22:51:29.775743

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ba7716dca30a'
down_revision = '8021be777d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('thumb_name', sa.String(), nullable=True))
    op.add_column('file', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'height')
    op.drop_column('file', 'width')
    op.drop_column('file', 'duration')
    op.drop_column('file', 'thumb_name')
    # ### end Alembic commands ###
