"""empty message

Revision ID: ff03785a1f0d
Revises: d3f89ea5e8b5
Create Date: 2022-06-10 20:04:34.792613

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ff03785a1f0d'
down_revision = 'd3f89ea5e8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('file', 'ext')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'file', sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column('file', 'title')
    # ### end Alembic commands ###
